# Generated by Django 5.0.1 on 2024-01-07 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
