# Generated by Django 5.0.1 on 2024-01-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
