# Generated by Django 5.0.1 on 2024-01-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_delete_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='skills',
            field=models.ManyToManyField(blank=True, to='Users.skill'),
        ),
    ]
