# Generated by Django 5.0.1 on 2024-02-12 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
