# Generated by Django 5.0.1 on 2024-02-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0018_ticket_paycode'),
        ('Users', '0010_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='staffs', to='Ticket.service'),
        ),
    ]
