# Generated by Django 5.0.1 on 2024-03-20 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_user_device_reg_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['department']},
        ),
    ]
