# Generated by Django 5.0.1 on 2024-04-18 07:21

import django.db.models.deletion
import gdstorage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='cat_icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('location', models.JSONField()),
                ('info_fields', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Rejected', 'Rejected by company'), ('Pending Approval', 'Pending for client approval'), ('Client Rejected', 'Rejected by client'), ('Pending Payment', 'Pending for client payment'), ('In Progress', 'In Progress'), ('Closed', 'Closed'), ('Rated', 'Rated')], db_index=True, default='Open', max_length=20)),
                ('client_rating', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('paycode', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['submission_date'],
            },
        ),
        migrations.CreateModel(
            name='TicketPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('initial_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('picture', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='serv_pictures/')),
                ('type', models.CharField(choices=[('Fixing', 'Fixing service'), ('Support', 'Support service'), ('Setting', 'Setting service')], default='Fixing', max_length=10)),
                ('is_final_price', models.BooleanField(default=False)),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Ticket.servicecategory')),
            ],
        ),
    ]
