# Generated by Django 5.0.1 on 2024-01-14 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0004_alter_ticket_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='client',
        ),
    ]
