# Generated by Django 5.0.1 on 2024-01-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0007_alter_ticket_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='picture',
            field=models.ImageField(default='file.png', upload_to='serv_pictures/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='icon',
            field=models.ImageField(default='icon.png', upload_to='cat_icons/'),
            preserve_default=False,
        ),
    ]
