# Generated by Django 5.0.1 on 2024-01-15 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0008_service_picture_servicecategory_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='discription',
            new_name='description',
        ),
    ]
