# Generated by Django 5.0.1 on 2024-02-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0010_alter_service_picture_alter_servicecategory_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('Fixing', 'Fixing service'), ('Support', 'Support service'), ('Setting', 'Setting service')], default='Fixing', max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='info_fields',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
