# Generated by Django 5.0.1 on 2024-02-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0012_remove_ticket_approved_service_is_final_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='title',
        ),
    ]
