# Generated by Django 5.0.1 on 2024-02-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0013_remove_ticket_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_paid',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Rejected', 'Rejected by company'), ('Pending Approval', 'Pending for client approval'), ('Client Rejected', 'Rejected by client'), ('Pending Payment', 'Pending for client approval'), ('In Progress', 'In Progress'), ('Closed', 'Closed'), ('Rated', 'Rated')], default='Open', max_length=20),
        ),
    ]
