# Generated by Django 5.0.1 on 2024-02-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0015_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='info_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
