# Generated by Django 5.0.1 on 2024-02-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0016_alter_ticket_info_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='location',
            field=models.JSONField(default={'alt': 33, 'long': 33}),
            preserve_default=False,
        ),
    ]
