# Generated by Django 5.0.1 on 2024-02-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0017_alter_ticket_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='paycode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
