# Generated by Django 5.0.1 on 2024-03-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0019_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
