# Generated by Django 5.0.1 on 2024-03-18 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0020_alter_ticket_submission_date'),
        ('Users', '0012_user_device_reg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_supervisor': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='Users.staff'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='workers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_supervisor': False}, related_name='tickets_assigned', to='Users.staff'),
        ),
    ]
