# Generated by Django 5.0.1 on 2024-04-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'new ticket'), (2, 'staff assign ticket'), (3, 'client reject'), (4, 'client accept'), (5, 'paid ticket'), (6, 'ticket rejected'), (7, 'ticket done'), (8, 'ticket rated')])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
