# Generated by Django 5.0.1 on 2024-03-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.IntegerField(choices=[(1, 'new ticket'), (2, 'staff assign ticket'), (3, 'client reject'), (4, 'client accept'), (5, 'paid ticket'), (6, 'ticket rejected')]),
        ),
    ]
