# Generated by Django 5.0.1 on 2024-03-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_seen',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
